site_name: 슈퍼컴퓨팅 기술지원 문서
site_url: https://docs-admin.github.io/neuron-guide/
use_directory_urls: true
theme:
  name: material
  font:
    text: Noto Sans KR  # 본문: 구글 본고딕 (가장 깔끔함)
    code: Nanum Gothic Coding
    
watch:
  - mkdocs.yml
  - docs
  
extra:
  use_directory_urls: true

extra_javascript: []
extra_css: []

plugins:
  - search
  - awesome-pages

# nav:
#   - 'Neuron 가이드':
#     - '메인' : 'neuron-guide/SUMMARY.md'
