site_name: 슈퍼컴퓨팅 기술지원 문서
site_url: https://docs-admin.github.io/neuron-guide/
use_directory_urls: true
theme:
  name: material

watch:
  - mkdocs.yml
  - docs
  - docs/neuron-guide  

extra:
  use_directory_urls: true

extra_javascript: []
extra_css: []

plugins:
  - search
  - awesome-pages

# nav:
#   - 'Neuron 가이드':
#     - '메인' : 'neuron-guide/SUMMARY.md'
