name: publish site
on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 실행
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin # 필요한 플러그인 포함
      - run: mkdocs gh-deploy --force # gh-pages 브랜치로 자동 배포
